server :
  port : 8082
  contextPath : /laCorneDabondance
spring :
  datasource :
   url : jdbc:mysql://localhost:3305/cornedabondance?useSSL=false
   driver-class-name: com.mysql.jdbc.Driver
   username: root
   password: racine