insert into user values ("dam","Fricot","Damien",0494129873,"damien.fricot@hotmail.be","Rue du moulin 220 5600 Philippeville","Avenue Fernand Golenvaux 5000 Namur",str_to_date('23-aug-1994','%e-%b-%Y'),'motDePasse',true);
insert into category values (1,"fruit"),(2,"légume");
insert into product values (1,
							"Pomme",
                            "Malus Domestica",
                            "Rosacée",
                            "Elstar",
                            0.2,
                            "Fruit local par excellence, la pomme est le seul fruit de nos régions que l’on peut consommer toute l’année.
                        Nous en mangeons en moyenne un peu plus de 16 kg par année.La pomme est énergisante et désaltérante.
                        Elle fait une collation parfaite car elle contient beaucoup de vitamines, de minéraux, d'oligoéléments, d'acides des fruits et de fructose.",
                        10,
                        str_to_date('8-8-2019','%e-%c-%Y'),
                        str_to_date('1-4-2019','%e-%c-%Y'),
                        str_to_date('30-11-2019','%e-%c-%Y'),
                        "pomme.png",
                        20,
                        1	),
                        (2,
							"Fraise",
                            "Fragaria virginiana",
                            "Rosacée",
                            "De Virginie",
                            0.7,
                            "Fruit rafraîchissant par excellence grâce à sa richesse en eau, la fraise présente de plus la particularité d'être fort peu énergétique : 52 calories pour une portion de 150 g, très raisonnable pour un dessert !",
                        3,
                        str_to_date('7-4-2019','%e-%c-%Y'),
                        str_to_date('1-4-2019','%e-%c-%Y'),
                        str_to_date('15-4-2019','%e-%c-%Y'),
                        "fraise.png",
                        0,
                        1	),
                        (3,
							"Poire",
                            "Pyrus communis",
                            "Rosacée",
                            "Conférence",
                            0.5,
                            "Les poires raffolent des étés très chauds et trés ensoleillés. La poire se place au deuxième rang des fruits indigènes les plus appréciés. Chaque habitant du pays en mange plus de 3 kilos par année.",
                        3,
                        str_to_date('5-10-2019','%e-%c-%Y'),
                        str_to_date('1-9-2019','%e-%c-%Y'),
                        str_to_date('30-4-2020','%e-%c-%Y'),
                        "poire.png",
                        0,
                        1	),
                         (4,
							"Mûre",
                            "Morus Nigra",
                            "Rosacée",
                            "Noire",
                            0.15,
                            "La mûre est connue pour être ramassée au bords des chemins sur les ronces à la fin de l'été. Cette petite baie juteuse, violet très sombre, est appréciée pour sa saveur typée et son parfum agréable. Elle est connue depuis très longtemps puisqu'elle est mentionnée dans la mythologie grecque. La ronce serait issue du sang versé par les titans lors de leurs affrontements avec les dieux. La mûre est aujourd'hui cultivée dans une large zone géographique. Riche en vitamines et minéraux, elle présente un apport particulièrement élevé en pigments aux propriétés antioxydantes. De nombreux remèdes ou solutions à bases de feuilles de mûres ont été transmises de génération en génération, par exemple pour renforcer les gencives ou soulager les ulcérations de la bouche.",
                        3,
                        str_to_date('10-8-2019','%e-%c-%Y'),
                        str_to_date('1-7-2019','%e-%c-%Y'),
                        str_to_date('30-10-2019','%e-%c-%Y'),
                        "mure.png",
                        50,
                        1);
                        